#! /bin/bash

USAGE="<command> [<args>]

The 'repository' commands are:

   create      Create and init a new repository
   track       Track another kdist repository

See 'kdist repository <command> --help for more information on a specific command."

#
# For now nothing interesting to see here.
#
kdist_subcommand=$1
shift


case $kdist_subcommand in
create|track)
	;;
*)
	usage
esac


source $libexecdir/kdist-$kdist_command--$kdist_subcommand "$@"


