#! /bin/bash

SUMMARY="Gives some information on a specific release"

USAGE="[--help] [--since=<since>] <module> [<rev>]

   rev       The release which the log should be started from
   since     A previous release since the log should be generated"

from=HEAD
since=
module=

while
	case $1 in
	--since=*)	since=${1#--since=} ;;
	-*)		usage ;;
	*)		break
	esac
do
	shift
done

case $# in
2)	from=$2   ;&
1)	module=${1%%/*} ;;
*)	usage
esac


kdist__cd_topdir

if test -z "$since"; then
	since=$(release__get_parent $from) || exit
fi

# for a given module, it returns the sha1 used by the main project
# for a specific rev.
release__get_module_sha1 () {
	line=$(git ls-tree $1 -- $2) &&
	read mode type sha1 unused <<<$line &&
	echo $sha1
}

log_kernel () {
	f=$(release__get_module_sha1 $1 kernel) &&
	s=$(release__get_module_sha1 $2 kernel) &&
	kdist__cd_repository kernel &&
	kdist whatchanged --header $f $s
}

log_configs () {
	set -o pipefail
	git diff --submodule $2 $1 -- configs |
	sed -e "1s/^Submodule/\*/"
}

log_kdist () {
	set -o pipefail
	git diff --submodule $2 $1 -- kdist |
	sed -e "1s/^Submodule/\*/"
}

for m in $(git submodule foreach -q 'echo $name')
do
	case $m in
	$module)
		log_$m $from $since
		exit
	esac
done

die "Unkown module '$module'"
