#! /bin/bash

SUMMARY="Set up a config for the tracked kernel"

USAGE="[--no-flavour] <pattern>"

with_flavour=yes

while :
do
	case $1 in
	--no-flavour)
		with_flavour= ;;
	-*)
		kdist__usage ;;
	*)
		break
	esac
	shift
done

if test $# -ne 1; then
	kdist__usage
fi

kdist__cd_repository kernel

#
# Find out the config file to install
#
for f in $(config__resolve_files "$1")
do
	[ -z "$config" ] ||
	die "The given pattern matches too many files."

	config=$f
done
test -z "$config" &&
die "The given pattern gives no match."

#
# Found.
#
echo "Installing $config"
config=$(kdist__get_repository configs)/$config

# Backup previous .config
! test -e .config || {
	echo "Previous config saved in .config.old"
	mv -f .config .config.old
} &&

# do the install.
cp $config .config &&

if ! test $with_flavour; then
	config__unset_symbol NAME .config
fi
