#! /bin/bash

USAGE="[--version] <command> [<args>]"

#
# Subcommands may need to invoke again kdist, be sure that the same
# version is used.
#
__kdist=$0
kdist () {
	$__kdist "$@"
}
export -f kdist

#
# The version can be changed during the installation.
#
KDIST_VERSION=v0.6

#
# This path is changed during installation.
#
LIBEXECDIR=$(dirname "$__kdist")
libexecdir=${KDIST_EXEC_PATH:-$LIBEXECDIR}
test -d "$libexecdir" || {
	echo >&2 "invalid exec-path '$libexecdir'"
	exit 1
}
libexecdir=$(readlink -f "$libexecdir")

#
# Include all kdist libraries
#
source $libexecdir/kdist--lib || exit

#
# Restricted mode is initialized here.
#
if test -z "$KDIST_RESTRICTED_MODE"; then
	if (kdist__cd_topdir 2>/dev/null); then
		export KDIST_RESTRICTED_MODE=no
		exec $(kdist__get_repository kdist)/kdist "$@"
	else
		export KDIST_RESTRICTED_MODE=yes
	fi
fi

while
	case "$#,$1" in
	*,--version)
		echo kdist version $(kdist__version)
		exit ;;
	*,-*|0,*)
		kdist__usage
		exit 1 ;;
	*)
		break;;
	esac
do
	shift
done

kdist_command=$1
shift
kdist__run_handler "$@"
