#! /bin/bash

SUMMARY="Give information about a kernel configuration"

USAGE="info [<path>]"

while
	case $1 in
	-*)	kdist__usage ;;
	*)	break
	esac
do
	shift
done

case $# in
0)	path=.config ;;
1)	path=$(readlink -f $1) ;;
*)	kdist__usage
esac

if ! test -f "$path"; then
	die "config file not found."
fi

name=$(config__read_flavour $path)
arch=$(config__read_architecture $path 2>/dev/null)
echo "name	:" ${name:-<undefined>}
echo "arch	:" ${arch:-<unsupported>}
