#! /bin/bash

SUMMARY="List the releases made for the project or the kernel"

USAGE="[--help] [-n<digit>] [-r] [<pattern>]"

#
# Main
#
declare -a tags
declare -i max_count
reverse=no

while
	case $1 in
	-n*)
		max_count=${1#-n} ;;
	-r)
		reverse=yes ;;
	-*)
		kdist__usage ;;
	*)
		break
	esac
do
	shift
done

case $# in
0)	pattern='*' ;;
1)	pattern=$1  ;;
*)	kdist__usage
esac



for tag in $(git tag -l "$pattern" | sort -V)
do
	if expr $tag : ".*-[[:digit:]]\+" >/dev/null; then
		tags[${#tags[*]}]=$tag
	fi
done
tags_len=${#tags[*]}

#
# Sort "tags" array using the bubble sort algorithm. It should be ok
# since the array is almost sorted already.
#
if [ -z "$max_count" ] || [ $max_count -gt $tags_len ]; then
	min_index=0
else
	min_index=$((tags_len - max_count))
fi

for ((last=$((tags_len-1)); last >= $min_index; last--)); do
	swaped=no
	for ((i=0; i < last; i++)); do
		j=$((i+1))
		version__cmp ${tags[i]} ${tags[j]}
		case $reverse,$? in
		no,1|yes,2)
			tmp=${tags[i]}
			tags[i]=${tags[j]}
			tags[j]=$tmp
			swaped=yes
		esac
	done
	[ $swaped = no ] && break
done

for ((i=$min_index; i < $tags_len; i++)); do
	echo ${tags[i]}
done
