#! /bin/bash

SUMMARY="Show the current project state"

USAGE="[--help]"

if test $# -gt 0; then
	kdist__usage
fi

#
# 'status' command is considered as restricted command because it
# should be available when a super project has just been cloned and
# kdist/ submodule is still empty.
#
# But other attempts to use update command outside a super project
# managed by kdist is incorrect.
#

kdist__get_topdir >/dev/null ||
die "Not in a kdist project."

kdist__cd_topdir &&
git submodule status
