#! /bin/bash

SUMMARY="Manage kernel and project releases"

USAGE="<command> [<args>]"

while
	case $1 in
	-*)	usage ;;
	*)	break
	esac
do
	shift
done

kdist_subcommand=$1
shift
kdist__run_handler "$@"
