#! /bin/bash

USAGE="<commands> [<args>]

The 'project' commands are

   init      Create a new kdist project
   summary   Show changes summary of the current project state
   status    Show the current project state
   update    Initialize a freshly cloned project

See 'kdist repository <command> --help for more information on a specific command."

while
	case $1 in
	-*)	usage ;;
	*)	break
	esac
do
	shift
done

kdist_subcommand=$1
shift
kdist__run_handler "$@"
