#! /bin/bash

USAGE="create packaging <path>"

while
	case $1 in
	-*)		usage ;;
	*)		break
	esac
do
	shift
done

if test $# -ne 1; then
	usage
fi

path=$1
mkdir "$path"
rsync -aq $templatedir/rpm "$path" &&
cd "$path" &&
git init -q &&
git add . &&
git commit -q -s -m "Initial creation"


