#! /bin/bash

USAGE="<command> [<args>]

The 'repository' commands are:

   master          Create a master repository to track your releases
   packaging       Create a repository to track you packaging changes

See 'kdist repository create <command> --help for more information on a specific command."

#
# For now nothing interesting to see here.
#
kdist_subsubcommand=$1
shift

case $kdist_subsubcommand in
master|packaging)
	;;
*)
	usage
esac


source $libexecdir/kdist-$kdist_command--create-$kdist_subsubcommand "$@"
