#! /bin/bash

USAGE="[--version] [--no-pager] <command> [<args>]"

#
# By default we want pipefail shell's option to be set. Subshells that
# don't cause a new copy of the shell to be executed inherit the shell
# option.  Other subshells could inherit the value too by exporting
# the `SHELLOPTS' variable (see man page).
#
set -o pipefail

#
# Most commands would be confused by GIT_DIR.
#
unset GIT_DIR

#
# Subcommands may need to invoke again kdist, be sure that the same
# version is used.
#
__kdist=$(readlink -f $0)
kdist () {
	$__kdist "$@"
}
export -f kdist

#
# The version can be changed during the installation.
#
KDIST_VERSION=v0.9

#
# 'libexecdir' is changed during installation.
#
LIBEXECDIR=$(dirname "$__kdist")
libexecdir=${KDIST_EXEC_PATH:-$LIBEXECDIR}
test -d "$libexecdir" || {
	echo >&2 "invalid exec-path '$libexecdir'"
	exit 1
}
libexecdir=$(readlink -f "$libexecdir")
libhookdir=$(dirname "$__kdist")/templates/hooks

#
# Include all kdist libraries
#
source $libexecdir/kdist--lib || exit

#
# Restricted mode is initialized here.
#
if test -z "$KDIST_RESTRICTED_MODE"; then
	if kdist__get_topdir >/dev/null; then
		export KDIST_RESTRICTED_MODE=no
		[ -f $(kdist__get_repository kdist)/kdist ] &&
		exec $(kdist__get_repository kdist)/kdist "$@"
	fi
	export KDIST_RESTRICTED_MODE=yes
fi

while
	case "$#,$1" in
	*,--version)
		echo kdist version $(kdist__version)
		exit ;;
	*,--no-pager)
		use_pager=no ;;
	*,-*)
		kdist__usage
		exit 1 ;;
	*)
		break;;
	esac
do
	shift
done

kdist_command=$1
shift
kdist__run_command "$@"
