#! /bin/bash

SUMMARY="Deal with kernel release operations"

USAGE="<command> [<args>]"

release__get_parent () {
	git describe --always --abbrev=0 $1~1
}

while
	case $1 in
	-*)	usage ;;
	*)	break
	esac
do
	shift
done

kdist_subcommand=$1
shift
kdist__run_handler "$@"
