#! /bin/bash

SUMMARY="Show what changed between releases"

USAGE="[-v] [--all] [--since=<since>] [<git-log opts>] [<rev>] [-- <module>]"

declare -a logs
declare -a gitopts
all=false
modules=
since=
until=HEAD

while :
do
	case "$1" in
	-v|--verbose)
		verbose=yes ;;
	-h|--he|--hel|--help)
		kdist__usage ;;
	--all)
		all=true ;;
	--since=*)
		since=${1#--since=} ;;
	--)
		break ;;
	-*)
		gitopts+=("$1") ;;
	*)
		break
	esac
	shift
done

case $# in
0)
	modules=project ;;
1)
	until=$1
	modules=project ;;
2|3)
	case $1,$2 in
	--,*)	modules=$2 ;;
	*,--)	until=$1; modules=$3;;
	*)	kdist__usage;;
	esac ;;
*)
	kdist__usage
esac


kdist__cd_topdir

if test -z "$since"; then
	since=$(release__get_parent $until) ||
	die "kdist-log failed to retrieve a parent release."
fi

if $all; then
	modules="project $(module__list)"
fi

log_kernel () (
	u=$(module__get_sha1 $until kernel) &&
	s=$(module__get_sha1 $since kernel) ||
	return

	kdist__cd_repository kernel
	tag_u=$(release__describe $u) &&
	tag_s=$(release__describe $s) &&
	#
	# Specify unconditionnaly 'upstream' and 'limit'. They will be
	# ignored if they're ancestors of merge-base(u,s).
	#
	kdist whatchanged --header $s $u ${tag_u%-*} ${tag_s%-*} 2>/dev/null
)

log_configs () {
	set -o pipefail
	git diff --submodule $since $until -- configs |
	sed -e "1s/^Submodule/\*/"
}

log_kdist () {
	set -o pipefail
	git diff --submodule $since $until -- kdist |
	sed -e "1s/^Submodule/\*/"
}

log_project () {
	echo "* Project $since..$(git describe --always $until)"
	git log --pretty=tformat:"  > %s" $since..$until
}

for m in $modules
do
	case $(type -t log_$m) in
	function)
		logs+=("$(log_$m)") || exit ;;
	*)
		die "Unkown module '$m'"
	esac
done

for i in ${!logs[*]}
do
	if test -n "${logs[$i]}"; then
		[ $i -gt 0 ] && echo
		echo "${logs[$i]}"
	fi
done
