#! /bin/bash

USAGE="track [<path>]"


while :
do
	case $1 in
	-*)	usage ;;
	*)	break
	esac
	shift
done

case $# in
0)
	kdist__get_repository ;;
1)
	kdist__set_repository "$1"
	echo "kdist is now using: $1"
	;;
*)
	usage
esac
