#!/bin/sh
#
# This hook checks that any commits pushed on this repository won't
# modify anything except 3rd party drivers.
#

refname="$1"
oldrev="$2"
newrev="$3"
upstream=mainline
zero="0000000000000000000000000000000000000000"

if [ -z "$GIT_DIR" ]; then
	echo >&2 "Don't run this script from the command line."
	echo >&2 " (if you want, you could supply GIT_DIR then run"
	echo >&2 "  $0 <ref> <oldrev> <newrev>)"
	exit 1
fi

if [ -z "$refname" -o -z "$oldrev" -o -z "$newrev" ]; then
	echo >&2 "Usage: $0 <ref> <oldrev> <newrev>"
	exit 1
fi

# if $newrev is 0000...0000, it's a commit to delete a ref therefore
# we don't need to do any checkings.
if [ "$newrev" = "$zero" ]; then
	exit 0
fi

newrev_type=$(git cat-file -t $newrev)

case "$refname","$newrev_type" in
refs/heads/*,commit)
	;;
*)
	# Don't care about anything else
	exit 0
esac

# Are we creating a new branch ?
if [ "$oldrev" = "$zero" ]; then
	git rev-list $newrev --not $upstream
else
	git rev-list $newrev --not $oldrev $upstream
fi |
git diff-tree --stdin --name-only | while read && read path
do
	case "$path" in
	3rd-party)
		continue ;;
	*)
		echo >&2 "You're not allowed to modify anything except"
		echo >&2 "3rd party drivers in this repository."
		exit 1 ;;
	esac
done
