#! /bin/bash
#
# This hook is minimalist, it's simply dump the rewritten commits list
# in a file whose path is given by KDIST_REWRITTEN_COMMIT_LIST
# environment variable.
#
# The rest is done by the kdist command which triggered this hook.
#

if test -z "$KDIST_REWRITTEN_COMMIT_LIST"; then
	echo >&2 "Warning: you called a git command ($1) that rewrited commits."
	echo >&2 "kdist is tracking some kernel commits for different purposes "
	echo >&2 "(tracking bug fixes for example), and calling git directly had"
	echo >&2 "by-passed the kdist tracking process."
	echo >&2
	echo >&2 "You should make sure that's not the case or fix it manually."
	echo >&2
	exit 1
fi

# Pass the list to kdist which handles the rest.
cat >"$KDIST_REWRITTEN_COMMIT_LIST"
